config/routes.rb
Testlogin::Application.routes.draw do

  resources :blog_comments

  root 'welcome#index'

  get "welcome/login"
  post "welcome/login_user"
  get "welcome/index"
  get "welcome/about"
  get "welcome/contact"

  resources :blog_entries

  resources :blogs

  resources :projects

  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :projects
	has_many :blogs
	has_many :blog_comments

	validates :phone, presence: true

	def full_name
		"#{first_name} #{last_name}"
	end

	def age
		current_date - date_of_birth
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :blogs]


  # add new field to User resource
  # called phone number

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    num_users = @users.length

    if num_users > 50
      @some_text = "hi guys! we have lots of users! we have #{num_users}"
    else
      @some_text = "bummer. only #{num_users} user"
    end
    

  end

  # GET /users/1
  # GET /users/1.json
  def show
    @projects = @user.projects

  end

  # GET /users/1/blogs
  def blogs

  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    # update phone
    @user.phone = number_to_phone(:phone)

    @user.save

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      #@user_id = params[:id]

      @user = User.find(params[:id])


    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :bio, :first_name, :last_name)
    end
end

app/helpers/users_helper.rb
module UsersHelper
	def send_text
		text = "hi there guys. you can find me in the helpers folder"
	end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
    <!--    <input id="user_email" name="user[email]" type="text" /> -->

  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
    <!--    <input id="user_email" name="user[email]" type="text" /> -->

  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.telephone_field :phone %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>
<b><%= send_text %></b>
<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Bio</th>
      <th>First name</th>
      <th>Last name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.bio %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% if @user.first_name == "TJ" %>
	This is TJ!
<% end %>

<% if @user.first_name == "Thomas" %>
	This is Thomas
<% end %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @user.bio %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

<h2>List TJ's projects</h2>
<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.user_id %></td>
        <td><%= project.description %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>